- README.md
This PR include:
- Instruccions to run project locally
#28
> docs(README): update readme file with instructions to run locally 

- docs/eos-learn/system-resources.md
- website/sidebars.json
#30  
1. Go to website
2.Open Learn EOSI
> docs(system-resources):create document

- .github/pull_request_template.md
- README.md
#49 
- Delete npm instructions
- Add contributors
1. Open README.md
> Update README file

- README.md
- docs/eos-learn/eosio-protocol.md
- docs/eos-learn/hello-world-contract.md
- website/siteConfig.js
SEO / 301 redirects #21
1. Go to `learn.eoscostarica.io` 301 redirect should point you to `guide.eoscostarica.io`
1. Go to `developers.eoscostarica.io` 301 redirect should point you to `guide.eoscostarica.io`
> change site config domain name

- .github/workflows/nodejs.yml
> Update GH action repo name

- docs/eos-learn/eosio-networks.md
- website/sidebars.json
EOSIO Networks #60 
1. Unfold the `Learn EOSIO` tab
> update docs with new content

- docs/community-resources/telegram-channels.md
- docs/tools/glossary.md
- website/sidebars.json
#68 Rethink Navigation Structure 
> update navigation structure

- website/siteConfig.js
> algolia Integration 

- docs/tools/glossary.md
This edit was made directly from GitHub
> Remove duplicate glossary entry

- docs/visual-resources/lifebank-logos.md
- website/sidebars.json
> update visual resources

- docs/open-source-projects.md
> Add NPM packages 

- website/docusaurus.config.js
#132 
1. Ruyn project locally.
1. View footer to home page
1. The content is available in both english and spanish
> docs(docusaurus.config.js):Fix text to footer

- website/docusaurus.config.js
- website/src/theme/Footer/index.js
#144 
1.Run project locally and see footer
> Desing(footer):Change footer for original docusaurus V2

- website/docs/agile-methodologies.md
> docs(agile-methodologies.md): add videos referents to content

- website/docs/open-source-projects.md
#149 
1. Go to open source project
> doc(open-source-projects.md): fix broke image links

- docs/tools/nodeos-command-line-reference.md
- docusaurus.config.js
- sidebars.js
#139 
1. Go to tools.
- add new doc to tools nodeos-command-line-reference.md
- modify sidebars
> docs(nodeos-command-line-reference.md): add new page to tools section

- sidebars.js
#158 
Delete link to block-producer why content is duplicate in consensus mechanism
1. Run proyect locally
> docs(sidebars.js): delete link to block-producer in Learn EOSIO

- docs/community-resources/eosio-networks.md
- docs/eos-learn/accounts-and-permissions.md
- docs/eos-learn/consensus-mechanism.md
- docs/eos-learn/dapp-development.md
- docs/eos-learn/devops.md
- docs/eos-learn/eos-blockchain.md
- docs/eos-learn/smart-contracts.md
- docs/eos-learn/system-resources.md
- docs/tutorials/hello-world-contract.md
- docs/tutorials/modern-cpp.md
- docs/tutorials/workflow-tutorial.md
> fix: update embedded videos

- docs/eos-learn/consensus-mechanism.md
- docs/eos-learn/eosio-protocol.md
- docs/eos-learn/smart-contracts.md
- docs/open-source-projects.md
- docs/tutorials/hello-world-contract.md
> Fix broke links

- docs/open-source-projects.md
- sidebars.js
1. Correct Evodex Link
1. Re organize sidebar items
> add evodex website

- docs/backend-boilerplate.md
- docs/tools/eosio-sdk-libraries.md
- This PR fixes build error due to broken link 
- removed extra content from backend boilerplate page
- added links to SDK libraries 
No issue exists
1. yarn start
1. go to SDK page under tools
> fix(backend boilerplate): fix broken link build error

- package.json
> feat(docusaurus): Update to version 2.0.0-alpha.62

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- package.json
Resolves #193
Resolves #201 
1. Check docusaurus package version
> feat(docusaurus): Update docusaurus version to alpha-70

- docs/community-resources/useful-links.md
Resolves #207  
1. Open Useful Links
1. Check new links
> update(useful-links): New links

- docs/tutorials/markdown-guide.md
- sidebars.js
Resolves #199 
1. Tutorials Tab
1. Open Markdown Guide Section
1. Check Content
> feat(docs): Add Markdown Guide Section

- docs/social-media-guidelines.md
Resolves #178 
1. Go to Social Media Guidelines.
2. Check content is right.
> docs(frontend)SocialMedia-Guidelines-178

- docs/social-media-guidelines.md
Resolves #232 
1. Go to Social Media Guidelines
> docs(frontend):Update Social Media Guidelines-232

- docs/community-resources/useful-links.md
Resolves #180 
1. Go to Community
1. Open Useful Links
> update(useful-links): add new links

- src/pages/index.js
Resolves #242 
1. Check title "Medium articles" in the home guide page is changed to blog posts
> feat(frontend): change-medium-title

- docs/eos-learn/eosio-core.md
- sidebars.js
Resolves #233   
1. Go to learn eos
1. Open EOSIO core
> feat(new section): Add a EOSIO Core Section

- docs/readme-file-template.md
Resolves #253  
1. Check text size is as desired
> fix(frontend): make readme template link bigger

- docs/devops.md
Resolves #237  
1.  Open DevOps
1. Check Content
> update(devops): Add new content

- docusaurus.config.js
Resolves #278  
1. Click Tutorials
> fix(docusaurus.config.js): fix link

- docs/devops.md
Resolves #275  
1. Check Devops
> fix(devops): update image

- docs/developer-tools.md
Resolves #262  
1. Open Our Favorite Tools 
1. Check Content
> update(developer-tools): add new content

- docs/kubernetes.md
- sidebars.js
Resolves #301  
1. Kubernetes Section
1. Check Content
> feat(kubernetes): new section

- docs/community-resources/useful-links.md
Resolves #308  
1. Check link is right
1.
1.
> feat(content): new link inside useful links section

- docs/developer-tools.md
Resolves #306 
1. Go to Our Favorite Tools
> docs(frontend): Add Vault in favorite tools

- docs/tutorials/private-network-installation.md
> docs: update private network tutorial

- docs/tutorials/node-installation.md
closes #329  
1. `yarn start`.
1. Go to `localhost:3000/docs/tutorials/node-installation` and see the changes.
> docs: update eosio node installation

- docs/tutorials/node-installation.md
- docs/tutorials/private-network-installation.md
> Fix empty link

- docs/open-source-projects.md
> docs: add gGoods to open source projects

- docs/open-source-projects.md
> Minimal doc tweaks

- docs/community-resources/useful-links.md
related to #330  
1. `yarn start`
> docs: add EOSCommunity.org Forums to useful links

- .github/pull_request_template.md
- docs/open-source-projects.md
- add networks being monitored by our dashboard
> Update dashboard urls

- docs/eos-learn/dapp-development.md
- Resolves #369 
2. Go to `localhost:3000`
3. Go to Developer Guidelines > Learn EOSIO > Dapp Development
> (docs): fix video links

- docs/eos-learn/blockchain-security.md
- docs/tutorials/markdown-guide.md
- Resolves #280
- Resolves #360
1. Run `yarn start` 
2. Go to `localhost:3000`
3. Go to Developer Guidelines>Learn EOSIO> Security 
4. Go to Developer Guidelines> Tutorials > Markdown Guide
> (FE): code review fix translation

- docs/eos-learn/blockchain-security.md
- docs/tutorials/markdown-guide.md
- package.json
- sidebars.js
- yarn.lock
- Resolves #280 
- Resolves #360 
1. Run `yarn start` 
2. Go to `localhost:3000`
3. Go to Developer Guidelines>Learn EOSIO> Security 
4. Go to Developer Guidelines> Tutorials > Markdown Guide
> (docs): add blockchain security video

- docs/eos-learn/accounts-and-permissions.md
- Resolves #359
2. Go to `localhost:3000`
3. Go to Developer Guidelines > Learn EOSIO > Accounts And Permissions
> (FE): code review change to Read more on EOSIO account creation

- docs/eos-learn/accounts-and-permissions.md
- Resolves #359 
1. Go to `localhost:3000`
1. Go to Developers Guidelines > Learn EOSIO > Accounts and Permissions
> (docs): update accounts-and-permissions

- docs/eos-learn/smart-contracts.md
- Resolves #400 
1. Go to `localhost:3000`
1. Go to Developers Guidelines > Learn EOSIO > Smart Contracts
> (docs): fix missing videos

- docs/eos-learn/smart-contracts.md
- Resolves #409 
1. Go to `localhost:3000`
1. Go to Developers Guidelines > Learn EOSIO > Smart Contract
> (docs): remove broken link

- docs/open-source-projects.mdx
- Resolves #417 
1. Go to `localhost:3000`
1. Go to Developers Guidelines > Open Source Projects
> feat(docs): add local environments section

- src/pages/index.js
- Resolves the link of Learn EOSIO card in homepage.
1. Run `yarn build`
2. Run `yarn start`
3. Go to `localhost:3000`
4. Go to Homepage > Cards
> (pages): fix card image

- docs/agile-methodologies.md
- Resolves #453 
1. clone repo
1. run yarn start
1. go to agile methodologies page
> fix(agile-methodologies): convert to title case #453

- docs/boilerplate.md
- docs/community-resources/eosio-networks.md
- docs/community-resources/telegram-channels.md
- docs/devops.md
- docs/eos-learn/dapp-development.md
- docs/eos-learn/eosio-components.md
- docs/eos-learn/ricardian-contracts.md
- docs/material-ui.md
- docs/open-source-guidelines.md
- docs/open-source-projects.mdx
- docs/pair-mob-programming.md
- docs/tools/block-explorers.md
- docs/tools/readme-file-template.md
- docs/tutorials/github-guide.md
- docs/tutorials/markdown-guide.md
- docs/tutorials/node-installation.md
- docs/tutorials/react-tutorial.md
- src/pages/index.js
- Resolves # 347
-The broken link in readme template
-
1.Enter to tools
2.Enter to Readme file template
3.Reload page
4.Click into click here
> 452 set up local development environments jm

- docs/visual-resources.md
- resolves #464 
1. Go to [Developer Guidelines](https://guide.eoscostarica.io/docs/open-source-guidelines)
2. Go to [Visual Resources](https://guide.eoscostarica.io/docs/visual-resources)
3. See the change
> fix(frontend): Wrong language fixed 

- docusaurus.config.js
- package.json
- src/pages/index.js
- src/theme/Footer/index.js
- yarn.lock
fix(frontend):Update dependencies
Update the old dependencies without breaking changes
- resolves #371 
1. Move between parts of the guide
> 371 update project dependencies

- docs/eos-learn/eosio-protocol.md
- docs/eos-learn/migration-to-mandel.md
- sidebars.js
- resolves #322
1. Go to "Learn EOSIO"
2. Open "EOSIO Protocol"
3. Check the content
4. Go to the sidebar and open "Migration from EOSIO to Mandel"
5. Check the content
> EOS, EOSIO and Mandel information

- docs/consensus-mechanisms-blockchain.md
- sidebars.js
- resolves #480
1. Go to Developer Guidelines
2. Go to Consensus Mechanisms Blockchain
1.
> feat(common): Add information above consensus mechanims #480

- docs/eos-learn/important-functions.md
- docs/open-source-projects.mdx
- docs/tools/glossary.md
- docs/tutorials/markdown-guide.md
- docs/tutorials/react-tutorial.md
- resolves #479 
1. Check that the translations of the changes are correct
> Wrong language on the English site

- docs/agile-methodologies.md
- docs/developer-tools.md
- docs/devops.md
- docs/tutorials/modern-cpp.md
- docs/visual-resources.md
- src/pages/index.js
- src/theme/Footer/index.js
- resolves #299
- For markdown images since Docusaurus [v2.0.0-beta.16](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.16) they are lazy-loaded
- Add loading lazily in pages with many images or embedded videos 
1. Check that the changes are correct
> perf: Add lazy loading

- docs/eos-learn/eos-network-foundation.md
- sidebars.js
- resolves #385 
1. Go to Learn EOSIO
2. Go to Blue Papers
> feat(frontend): Add information about Blue Papers #385

- docs/eos-learn/eos-blockchain.md
- docs/eos-learn/eosio-components.md
- docs/material-ui.md
- docs/social-media-guidelines.md
- docs/tools/readme-file-template-source-code.md
- docs/tools/readme-file-template.md
- src/pages/index.js
- resolves #264
1. Review the files changed
2. Check that images are not missing on those pages
> refactor(frontend): update image referencing

- docs/open-source-guidelines.md
- resolves #493
1. Go to 'Developer Guidelines'
2. Click on 'Open source Guidelines'
3. Go to Branch Naming Convention and the list of types should not appear
> fix(frontend): delete duplicate list

- docs/engineering-culture.md
> Update guidelines content

- docusaurus.config.js
- src/pages/index.js
- resolves #424 
1. See the changes in homepage
> chore(frontend): improve meta description

- docs/community-resources/useful-links.md
- docs/eos-learn/smart-contracts.md
- docs/tools/example-eosio-smart-contract.md
- sidebars.js
- resolves #495
- resolves #500 
1. Go to LearnEOSIO/SmartContracts
2. Go to Community/UsefulsLinks
> feat(frontend): Adding useful link ENG #495 and #500

- docs/community-resources/eosio-networks.md
- docs/community-resources/useful-links.md
- docs/developer-tools-ux-ui.md
- docs/eos-learn/accounts-and-permissions.md
- docs/eos-learn/block-producer.md
- docs/eos-learn/blockchain-security.md
- docs/eos-learn/consensus-mechanism.md
- docs/eos-learn/dapp-development.md
- docs/eos-learn/eos-blockchain.md
- docs/eos-learn/eos-network-foundation.md
- docs/eos-learn/eosio-components.md
- docs/eos-learn/eosio-protocol.md
- docs/eos-learn/important-functions.md
- docs/eos-learn/migration-to-mandel.md
- docs/eos-learn/nft-on-eosio.mdx
- docs/eos-learn/ricardian-contracts.md
- docs/eos-learn/smart-contracts.md
- docs/eos-learn/system-resources.md
- docs/tools/command-line.md
- docs/tools/frequently-asked-questions.md
- docs/tools/glossary.md
- docs/tools/readme-file-template-source-code.md
- docs/tools/readme-file-template.md
- docs/tools/sample-nodeos-configs.md
- docs/tutorials/how-to-mint.mdx
- ran spell check 
- improve sidebar labels
- improve meta descriptions and keywords
> fix(docs): Run spell check and content review

- docs/eos-learn/migration-to-mandel.md
- resolves #issueNumber
1.
1.
1.
> fix(docs): adjust keywords

- docusaurus.config.js
- src/pages/index.js
- resolves #516 
1. Go to Homepage and click on switch theme
> fix(bug): Change to correct function ENG #516

- docusaurus.config.js
- package.json
- yarn.lock
- enable sitemaps
1. clone repo 
1. yarn install
1. yarn run
> enable sitemaps

- docusaurus.config.js
- static/scripts/fix-location.js
- resolves #465 
1. Go to tools
2. Go to Readme
3. Reload the page
4. Check don't appear this slash
> fix(frontend): Adding trailingSlash #465 ENG

- package.json
- yarn.lock
- resolves #519
1. Check the changed files
> feat: update docusaurus version #519

- docusaurus.config.js
> Optimize page title

- CONTRIBUTING.md
- docs/community-resources/blog-posts.md
- docs/consensus-mechanisms-blockchain.md
- docs/developer-tools.md
- docs/engineering-culture.md
- docs/eos-learn/dapp-development.md
- docs/eos-learn/eos-network-foundation.md
- docs/eos-learn/eosio-components.md
- docs/eos-learn/important-functions.md
- docs/eos-learn/ricardian-contracts.md
- docs/eos-learn/system-resources.md
- docs/material-ui.md
- docs/tools/frequently-asked-questions.md
- docs/tools/readme-file-template.md
- docs/tutorials/docker.md
- docs/tutorials/github-guide.md
- docs/tutorials/github-keys.md
- docs/tutorials/kubernetes.md
- docs/tutorials/markdown-guide.md
- docs/tutorials/node-installation.md
- docs/tutorials/private-network-installation.md
- docs/tutorials/react-tutorial.md
- resolves #523 
1. Go to browser in VSCode and search "[link]"
> refactor(frontend): new descriptive hyperlink ENG #523

- docs/tools/readme-file-template-source-code.md
- docs/tools/readme-file-template.md
- resolves https://github.com/eoscostarica/guias.eoscostarica.io/issues/378
1. Go to https://guias.eoscostarica.io/docs/herramientas/plantilla-readme and click on 'click here'
> docs(common):Fix Readme Template ENG #378

- docs/tools/readme-file-template.md
- makes for an SEO friendly link to markdown source code page
1. Go To https://guide.eoscostarica.io/docs/tools/readme-file-template
2. See link
> docs(common): SEO friendly mardkdown

- CODE_OF_CONDUCT.md
- docs/eos-learn/ricardian-contracts.md
- docs/tutorials/private-network-installation.md
> replace eosio.cr domain with edenia.cloud

- src/theme/Footer/index.js
- resolves #553 
Adds link to edenia in copyright
> update copyright message

- src/theme/Footer/index.js
> fix(theme): improved footer logos interaction
